import os
print("ALL")
os.system("python imageMultiClassifier.py ALL_Bayesian CV_Bayesian ALL_DecisionTree CV_DecisionTree ALL_Logistic CV_Logistic ALL_MLP CV_MLP ALL_RandomForest CV_RandomForest ALL_SVM CV_SVM")
print("Alexnet")
os.system("python imageMultiClassifier.py Alexnet_DecisionTree Alexnet_RandomForest Alexnet_MLP Alexnet_Bayesian Alexnet_SVM")
print("FCN-16s")
os.system("python imageMultiClassifier.py FCN-16s_DecisionTree FCN-16s_RandomForest FCN-16s_MLP FCN-16s_NaiveBayes  FCN-16s_SVM")
print("InceptionV3")
os.system("python imageMultiClassifier.py Inception_DecisionTree Inception_RandomForest Inception_MLP Inception_Bayesian Inception_SVM")
print("Mobilenets160")
os.system("python imageMultiClassifier.py Mobilenets160_DecisionTree Mobilenets160_RandomForest Mobilenets160_MLP Mobilenets160_Bayesian Mobilenets160_SVM")
print("Network-in-Network")
os.system("python imageMultiClassifier.py Network-in-Network_DecisionTree Network-in-Network_RandomForest Network-in-Network_MLP Network-in-Network_NaiveBayes  Network-in-Network_SVM")
print("ResNet")
os.system("python imageMultiClassifier.py ResNet_DecisionTree ResNet_RandomForest ResNet_MLP ResNet_NaiveBayes ResNet_RandomForest ResNet_SVM")
print("VGG-16")
os.system("python imageMultiClassifier.py VGG-16_DecisionTree VGG-16_RandomForest VGG-16_MLP VGG-16_NaiveBayes  VGG-16_SVM")